[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/kaart"
  to = "/kaart/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

